# Generated by Django 4.1.7 on 2023-09-18 19:13

from django.db import migrations, models
import servercafe.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Masuk",
            fields=[
                ("jam_masuk", models.DateTimeField(auto_created=True)),
                (
                    "id",
                    models.IntegerField(
                        default=servercafe.models.randomin,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("jam_keluar", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
