# Generated by Django 4.1.7 on 2023-09-27 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("servercafe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="masuk",
            name="jam_keluar",
        ),
    ]
