# Generated by Django 4.1.7 on 2023-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servercafe", "0005_alter_masuk_jam_masuk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masuk",
            name="jam_masuk",
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
