# Generated by Django 4.1.7 on 2023-09-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="gambar",
            field=models.ImageField(default=2, upload_to=""),
            preserve_default=False,
        ),
    ]
