# Generated by Django 4.1.7 on 2023-09-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_alter_menu_gambar"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="kategori",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Makanan", "Makanan"),
                    ("Minuman", "Minuman"),
                    ("Side Dish", "Side Dish"),
                ],
                max_length=30,
            ),
        ),
    ]
